In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [5]:
type(x)

numpy.ndarray

In [6]:
# vector addition

x = np.array([1,2,3])
y = np.array([4,5,6])
z = x+y
z

array([5, 7, 9])

In [7]:
# element wise multiplication

z = x*y
z

array([ 4, 10, 18])

In [8]:
# vector scaling 

x = np.array([1,2,3])
y = 3*x
y

array([3, 6, 9])

In [9]:
# exponent

z = np.array([1,2,3,4])
x = z**2
x

array([ 1,  4,  9, 16])

In [10]:
x = np.array([1, 10, 100, 1000, 10000, 100000])
y = np.log10(x)
y

array([0., 1., 2., 3., 4., 5.])

In [11]:
# natural log

x = np.array([1, np.e, np.e ** 2])
y = np.log(x)
y

array([0., 1., 2.])

In [12]:
# dot product

x = np.array([1,2,3,4])
y = np.array([-4,-5,-6,-7])

z = np.dot(x,y)
z

-60

In [13]:
x = np.array([10, 20, 30, 40])
x.shape

(4,)

In [14]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [15]:
x = np.ones(4)
x

array([1., 1., 1., 1.])