In [1]:
import numpy as np

In [2]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# adding two matrices

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B
C

array([[ 6,  8],
       [10, 12]])

In [4]:
# vector scaling 

M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
P = 3 * M
P

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [5]:
# element wise multiplication

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A * B
C

array([[ 5, 12],
       [21, 32]])

In [6]:
A = np.array([[-1, 2], [-3, -4]])
f_A = np.abs(A)   # np.abs returns the absolute value

f_A

array([[1, 2],
       [3, 4]])

In [7]:
A = np.array([[1, 2], [3, 4]])
B = A ** 2

B

array([[ 1,  4],
       [ 9, 16]])

In [8]:
# Transpose matrix

M = np.array([[1, 2, 3], [4, 5, 6]])
M_t = np.transpose(M)

M_t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M_t = M.T

M_t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
# product of two matrices

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 7], [8, 9], [10, 11]])

C = A @ B
C

array([[ 52,  58],
       [124, 139]])

In [12]:
# product of a matrix and a vector

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([6, 7, 8])
C = A @ x

C

array([ 44, 107, 170])

In [13]:
# shape of a matrix

M = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
M.shape

(4, 2)

In [14]:
M = np.zeros((2, 4))
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# identity matrix

I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])